//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public Movie()
        {
            this.Screenings = new HashSet<Screening>();
        }
    
        public int MovieId { get; set; }
        public string Title { get; set; }
        public System.TimeSpan Duration { get; set; }
    
        public virtual ICollection<Screening> Screenings { get; set; }
    }
}
