//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screening
    {
        public int ScreeningId { get; set; }
        public Nullable<int> MovieId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> Occupency { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual Room Room { get; set; }
    }
}
